version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: liquibase-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=5ecurityP@ssword
      - MYSQL_DATABASE=liquibase-create
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306